version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/cc/dockers/sonarr/sonarr-data:/config
      - /mnt/media:/mnt/media #optional

    ports:
      - "192.168.3.249:8989:8989"
    restart: unless-stopped