version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    #runtime: nvidia # Expose NVIDIA GPUs
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
      - TZ=America/Los_Angeles
    volumes:
      - /home/cc/dockers/emby/config:/config # Configuration directory
      - /mnt/media:/mnt/media # Media directory
    ports:
      - "192.168.3.250:8096:8096" # HTTP port
      - "192.168.3.250:8920:8920" # HTTPS port
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # VAAPI/NVDEC/NVENC render nodes

    #  - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: always