version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/cc/dockers/radarr/radarr-data:/config
      - /mnt/media:/mnt/media #optional

    ports:
      - "192.168.3.249:7878:7878"
    restart: unless-stopped