version: '3.3'

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "/home/cc/dockers/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Los_Angeles"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=5 20 * * thu"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      # - "DIUN_NOTIF_SLACK_WEBHOOKURL="
      - "DIUN_NOTIF_SLACK_RENDERFIELDS=false"
      #- "DIUN_NOTIF_SLACK_TEMPLATEBODY=<!channel> Docker tag {{ if .Entry.Image.HubLink }}<{{ .Entry.Image.HubLink }}|`{{ .Entry.Image }}`>{{ else }}`{{ .Entry.Image }}`{{ end }}  {{ if (eq .Entry.Status 'new') }}available{{ else }}updated{{ end }}."
    restart: always



# notes: DIUN_NOTIF_SLACK_WEBHOOKURL set this to have slack notificaitons.