---
version: "2.1"
services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - CONFIGFILE=/config/adguardhome-sync.yaml
    volumes:
      - /home/cc/dockers/adguardhome-sync/adguardhome-sync-data:/config
    ports:
      - "7000:8080"
    restart: unless-stopped