version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/cc/dockers/bazarr/bazarr-data:/config
      - /mnt/media:/mnt/media
    ports:
      - "192.168.3.249:6767:6767"
    restart: unless-stopped