version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/cc/dockers/lidarr/lidarr-data:/config
      - /mnt/media/Music:/music #optional

      - /mnt/media:/mnt/media
    ports:
      - "192.168.3.249:8686:8686"
    restart: unless-stopped